#!/usr/bin/env ansible-playbook
---

#######
# All #
#######

# just for debug.
debug_mode: false

#disable exposing php version
php_expose: 'Off'

# allow_url_fopen
#   Default Value: On
php_allow_url_fopen: "Off"

php_disable_functions: "exec,passthru,shell_exec,system,proc_open,popen"
php_display_errors: "Off"
php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"

# disable exposing php version.
#   Default Value: On
php_expose_php: 'Off'

php_memory_limit: "1024M"
php_opcache_enable: 1
php_opcache_revalidate_freq: 0
php_post_max_size: "20M"
php_serialize_precision: 17
php_session_cookie_httponly: 1
php_session_use_strict_mode: 1
php_soap_wsdl_cache_dir: '/php/cache/wsdl'
php_timezone: "UTC"
php_upload_max_filesize: "20M"
php_upload_tmp_dir: "/php/cache/upload_tmp"

# Note: we need use 'www-data' on Debian 8.
php_owner: 'nginx'
php_group: 'nginx'

##########
# CentOS #
##########

#yum_php_version: "70u"
yum_php_version: "71u"

yum_php_packages:
  - php{{ yum_php_version }}-cli
  - php{{ yum_php_version }}-common
  - php{{ yum_php_version }}-fpm
  - php{{ yum_php_version }}-fpm-nginx
  - php{{ yum_php_version }}-pdo
  - php{{ yum_php_version }}-mysqlnd
  - php{{ yum_php_version }}-pecl-imagick
  - php{{ yum_php_version }}-bcmath
  - php{{ yum_php_version }}-pecl-amqp
  - php{{ yum_php_version }}-mcrypt

# PHP-FPM FastCGI.
centos_php_fastcgi_listen: "/run/php-fpm/www.sock"
centos_nginx_fastcgi_server: "unix:{{ centos_php_fastcgi_listen }}"

redis_version: 4.0.0
redis_bind: 127.0.0.1

mysql_root_password: saazie7ZOoX1loob
#mysql_version: 5.7.19
mysql_version: 5.6

# Pass in a comma-separated list of repos to use (e.g. "remi,epel"). Used only
# for RHEL/CentOS.
phpmyadmin_enablerepo: epel

# Override if needed. This is set platform-specific in the vars dir if not set.
# phpmyadmin_config_file: /etc/phpmyadmin/config.inc.php
phpmyadmin_config_file: /usr/share/phpmyadmin/config.inc.php

phpmyadmin_mysql_host: localhost
phpmyadmin_mysql_port: ""
phpmyadmin_mysql_socket: ""
phpmyadmin_mysql_connect_type: tcp
phpmyadmin_mysql_user: root
phpmyadmin_mysql_password: "{{ mysql_root_password }}"

nginx_remove_default_vhost: true
nginx_vhosts:
  - listen: "80 default_server"
    server_name: "_"
    root: "/var/www/html"
    index: "index.php index.html index.htm"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "example.com.conf"
    extra_parameters: |
      location /phpmyadmin {
        root /usr/share/;
        index index.php index.html index.htm;
        location ~ ^/phpmyadmin/(.+\.php)$ {
          try_files $uri =404;
          root /usr/share/;
          fastcgi_pass unix:/run/php-fpm/www.sock";
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include /etc/nginx/fastcgi_params;
        }
      }
      location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
        root /usr/share/;
      }
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/run/php-fpm/www.sock";
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }



# vim: ft=yaml.ansible :
